# build tools
FROM golang as builder

COPY ./ /projects/tool/
WORKDIR /projects/tool/
RUN make


# final image
FROM debian:stable-slim

COPY --from=builder /projects/tool/cmd/* /usr/local/bin/
RUN ls -l /usr/local/bin